### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by zygimantus** [Karumi/MarvelApiClientAndroid#17]
In my application I was trying to serialize the MarvelResponse object but I got this excepion: 

Caused by: java.io.NotSerializableException: com.karumi.marvelapiclient.model.MarvelResponse
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.springframework.util.SerializationUtils.serialize(SerializationUtils.java:45)
	... 36 more

What was the reason that this class does not implement Serializable?

**Comment by Serchinastico** [comment]
Hi @zygimantus 

We didn't find the need to make it implement `Serializable`, what's your use case?

**Comment by zygimantus** [comment]
Thank you for your answer, @Serchinastico. I think I will get over it without using using serialization.
